### PR TITLE
Add require_signature_auth parameter

### PR DESCRIPTION
**Pull request by Etienne-Carriere**

### CODE REVIEW

**Comment by Etienne-Carriere** [comment]
As discussed with @kvz, I pushed 2 new commits for having a boolean in the external interface for require_signature_auth

**Comment by Acconut** [comment]
Thank you very much, @Etienne-Carriere! It's a bit unfortunate that the Transloadit API only accepts 0/1 and no booleans requiring these workarounds. However, I think it would be better from an implementation point to add `MarshalJSON` and `UnmarshalJSON` functions to the `Template` struct (see https://golang.org/pkg/encoding/json/#example__customMarshalJSON) instead of the `setFromInternal` functions. These methods would take care of the boolean to integer (and vice versa) conversion using the `templateInternal` struct. The benefit is that the Go SDK internally cannot forget to call `setFromInternal` because Go's encoding/json package will take care of calling our custom JSON function. What to you think?

**Comment by Etienne-Carriere** [comment]
@Acconut , I  am not accustomed to json golang library. If you have time, could you please show me how to do ?

**Comment by Acconut** [comment]
No worries, let me see if I can quickly make the changes by myself to unblock your Terraform PR.

**Review by Acconut — APPROVED** [review]

**Comment by Acconut** [comment]
I published go-sdk v1.2.0 with this PR.

**Pull request merged**
